<?php

namespace LegacyProductAttributes\Model;

use LegacyProductAttributes\Model\Base\LegacyProductAttributeValuePriceQuery as BaseLegacyProductAttributeValuePriceQuery;

class LegacyProductAttributeValuePriceQuery extends BaseLegacyProductAttributeValuePriceQuery
{

}
