<?php

namespace LegacyProductAttributes\Model;

use LegacyProductAttributes\Model\Base\LegacyOrderProductAttributeCombination as BaseLegacyOrderProductAttributeCombination;

class LegacyOrderProductAttributeCombination extends BaseLegacyOrderProductAttributeCombination
{

}
