<?php

namespace LegacyProductAttributes\Model;

use LegacyProductAttributes\Model\Base\LegacyCartItemAttributeCombinationQuery as BaseLegacyCartItemAttributeCombinationQuery;

class LegacyCartItemAttributeCombinationQuery extends BaseLegacyCartItemAttributeCombinationQuery
{

}
